// <auto-generated />
using System;
using Clinic.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clinic.Web.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    partial class ClinicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Clinic.Entities.City", b =>
                {
                    b.Property<int>("City_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("State_Id")
                        .HasColumnType("int");

                    b.HasKey("City_Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Clinic.Entities.Country", b =>
                {
                    b.Property<int>("Country_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Country_Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Clinic.Entities.Discharge", b =>
                {
                    b.Property<int>("Patient_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Advance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Chief_Complain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date_of_Discharge")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_on_Admit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day_Stayed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Doctor_Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Doctor_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Extra_Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("F_H_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("In_Out_Patient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Medicine_Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Patient_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patient_Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patient_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Room_Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Room_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Test_Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Time_of_Discharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Total_Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("time_of_Admit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Patient_Id");

                    b.ToTable("Discharges");
                });

            modelBuilder.Entity("Clinic.Entities.Disease", b =>
                {
                    b.Property<int>("Disease_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Disease_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doctor_Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Disease_Id");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("Clinic.Entities.Doctor", b =>
                {
                    b.Property<int>("Doctor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doctor_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doctor_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoginId")
                        .HasColumnType("int");

                    b.Property<int?>("Specialist_Id")
                        .HasColumnType("int");

                    b.Property<string>("TimeFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeTo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Doctor_Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Clinic.Entities.DoctorCharges", b =>
                {
                    b.Property<string>("Patient_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Charge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Doctor_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Patient_Code");

                    b.ToTable("DoctorCharges");
                });

            modelBuilder.Entity("Clinic.Entities.Medicine", b =>
                {
                    b.Property<int>("Medicine_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Batch_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Exp_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Medicine_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicine_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Mfg_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Medicine_Id");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("Clinic.Entities.Patient", b =>
                {
                    b.Property<int>("Patient_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Advance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date_of_Admit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Doctor_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_H_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("I_O_Patient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patient_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patient_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time_Admit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Patient_Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Clinic.Entities.Room", b =>
                {
                    b.Property<int>("Room_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Room_Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Clinic.Entities.RoomCharges", b =>
                {
                    b.Property<string>("Patient_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date_on_Room_Given")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RoomCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Room_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time_of_Room_Given")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Patient_Code");

                    b.ToTable("RoomCharges");
                });

            modelBuilder.Entity("Clinic.Entities.SpecialVisitDoctor", b =>
                {
                    b.Property<int>("Doctor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doctor_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doctor_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Specialist_Id")
                        .HasColumnType("int");

                    b.HasKey("Doctor_Id");

                    b.ToTable("SpecialVisitDoctors");
                });

            modelBuilder.Entity("Clinic.Entities.Specialist", b =>
                {
                    b.Property<int>("Specialist_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Special_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialist_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Specialist_Id");

                    b.ToTable("Specialists");
                });

            modelBuilder.Entity("Clinic.Entities.State", b =>
                {
                    b.Property<int>("State_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Country_Id")
                        .HasColumnType("int");

                    b.Property<string>("State_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("State_Id");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Clinic.Entities.Test", b =>
                {
                    b.Property<int>("Test_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Test_Id");

                    b.ToTable("Test");
                });
#pragma warning restore 612, 618
        }
    }
}
